version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jvillalba
      POSTGRES_PASSWORD: 12345@
      POSTGRES_DB: nest_db
    ports: 
      - "5490:5432"